#!/bin/sh -e

export PREFIX=""
if ["$TOX" != "true"] && [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

export EXTRA_COVERAGE_FLAGS=""
if [ "$TRAVIS" != "true" ] ; then
    # If we're on travis we'll allow codecov to handle coverage pass/fail.
    # Locally we enforce 100% coverage, once all tests are passing.
    export EXTRA_COVERAGE_FLAGS="--cov-fail-under=100 --no-cov-on-fail"
fi

set -x

# PYTHONPATH=. ${PREFIX}pytest --ignore venv --cov=besepa ${EXTRA_COVERAGE_FLAGS} ${@}
PYTHONPATH=. ${PREFIX}pytest --ignore venv ${@}
